### 滞在者数を取得
GET https://campuscrowdmonitor-api.sysken.net/api/v1/staycount/get/ HTTP/1.1
Content-Type: application/json
Accept: application/json

### 混雑度を取得
GET https://campuscrowdmonitor-api.sysken.net/api/v1/congestion/get/ HTTP/1.1
Content-Type: application/json
Accept: application/json

### 滞在者数の履歴を取得
GET http://campuscrowdmonitor-api.sysken.net/api/v1/staycount/histories/ HTTP/1.1
Content-Type: application/json
Accept: application/json

### 滞在者数の履歴を取得。部屋番号指定・期間指定
GET https://campuscrowdmonitor-api.sysken.net/api/v1/staycount/history/28/?date=2023-10-06 HTTP/1.1
Content-Type: application/json
Accept: application/json

### 滞在者数を登録
POST https://campuscrowdmonitor-api.sysken.net/api/v1/staycount/post/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "time" : "2022-09-04T19:09:48.000Z",
    "headcount" : 20
}

### Swagger
https://campuscrowdmonitor-api.sysken.net/api/v1/swagger/index.html

