import "@/styles/globals.css";
import styles from "@/styles/Home.module.scss";
import Head from "next/head";
import type { AppProps } from "next/app";
import Header from "@/components/base/header/header";
import { Noto_Sans_JP } from "next/font/google";
import { RecoilRoot } from "recoil";

const noto = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["100", "300", "500", "700", "900"],
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <RecoilRoot>
      <Head>
        <title>工科展</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={noto.className}>
        <Header />
        <main className={styles.main}>
          <Component {...pageProps} />
        </main>
      </div>
    </RecoilRoot>
  );
}
