definitions:
  model.GetCongestionBuildingModel:
    properties:
      building:
        type: string
      floors:
        items:
          $ref: '#/definitions/model.GetCongestionFloorModel'
        type: array
    type: object
  model.GetCongestionFloorModel:
    properties:
      areas:
        items:
          $ref: '#/definitions/model.GetCongestionRoomModel'
        type: array
      floor:
        type: integer
    type: object
  model.GetCongestionResponseModel:
    properties:
      building:
        items:
          $ref: '#/definitions/model.GetCongestionBuildingModel'
        type: array
    type: object
  model.GetCongestionRoomModel:
    properties:
      congestion:
        type: number
      id:
        type: integer
      name:
        type: string
    type: object
  model.GetStayCountBuildingModel:
    properties:
      building:
        type: string
      floors:
        items:
          $ref: '#/definitions/model.GetStayCountFloorModel'
        type: array
    type: object
  model.GetStayCountFloorModel:
    properties:
      areas:
        items:
          $ref: '#/definitions/model.GetStayCountRoomModel'
        type: array
      floor:
        type: integer
    type: object
  model.GetStayCountHistoryModel:
    properties:
      "0":
        items:
          type: integer
        type: array
    type: object
  model.GetStayCountHistoryRequestModel:
    properties:
      histories:
        items:
          $ref: '#/definitions/model.GetStayCountHistoryModel'
        type: array
    type: object
  model.GetStayCountResponseModel:
    properties:
      building:
        items:
          $ref: '#/definitions/model.GetStayCountBuildingModel'
        type: array
    type: object
  model.GetStayCountRoomModel:
    properties:
      id:
        type: integer
      name:
        type: string
      staycount:
        type: integer
    type: object
  model.PostStayCountRequestModel:
    properties:
      headcount:
        type: integer
      time:
        type: string
    type: object
info:
  contact: {}
  description: このswaggerはCampusCrowdMonitorのapiです
  title: CampusCrowdMonitor
  version: "1.0"
paths:
  /api/v1/congestion/get/{building_name}:
    get:
      description: 混雑度は、今までの滞在者数の最大値 / 現在の滞在者数で求める。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetCongestionResponseModel'
      summary: 混雑度を取得する
  /api/v1/staycount/get/{building_name}:
    get:
      description: arpscanによって取得したデータを元に滞在者数を取得する、滞在者数は最新のものを取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetStayCountResponseModel'
      summary: 滞在者数を取得する
  /api/v1/staycount/histories/:
    get:
      description: 滞在者数の履歴を取得する。これは24時間分のデータを取得する。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetStayCountHistoryRequestModel'
      summary: 滞在者数の履歴を取得する（今日だけ）
  /api/v1/staycount/history/{room_id}:
    get:
      description: 滞在者数の履歴を取得する。これは24時間分のデータを取得する。
      parameters:
      - description: '日付データを記載する 例: 2021-10-01'
        in: query
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetStayCountHistoryModel'
      summary: 滞在者数の履歴を取得する。部屋指定かつ日付指定
  /api/v1/staycount/post/{building_name}:
    post:
      description: arpscanによって取得したデータを元に滞在者数を登録する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PostStayCountRequestModel'
      summary: 滞在者数を登録する
swagger: "2.0"
